yolo_model:

  config_file:
    name: yolov4-tiny.cfg
  weight_file:
    name: yolov4-tiny.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - dur
      - durak
      - saga_donulmez
      - sola_donulmez
      - giris_olmayan_yol
      - tasit_giremez
      - park_yasak
      - park_yeri
      - ileri_veya_sola_mecburi_yon
      - ileri_veya_saga_mecburi_yon
      - sola_mecburi_yon
      - saga_mecburi_yon
      - kirmizi_isik
      - sari isik
      - yesil_isik
